test_cfutils_634850_633646: test_cfutils.c File Reference
test_cfutils.c File Reference
#include "utils/cfutils.h"
#include "CUnit/Basic.h"
Functions
void ctrl_full_FILE (list *list_people)
void ctrl_FILE_AL_male (list *list_people)
void ctrl_FILE_MZ_female (list *list_people)
void test_is_male (void)
void test_is_female (void)
void test_is_surname_AL (void)
void test_is_surname_MZ (void)
void test_filter_people (void)
void test_generate_cfs (void)
void test_read_birth_place_code (void)
void test_read_person (void)
void test_people_file_to_list (void)
void test_list_to_file (void)
void test_list_to_file_males_AL (void)
void test_list_to_file_females_MZ (void)
void test_people_to_file_cf (void)
void test_people_to_file_cf_males_AL (void)
void test_people_to_file_cf_females_MZ (void)
void test_outfile_path (void)
int init_suite_default (void)
int clean_suite_default (void)
int main ()
Function Documentation
int clean_suite_default (void)
Definition at line 657 of file test_cfutils.c.
Referenced by main().
void ctrl_FILE_AL_male (list * list_people)
Verifica che il contenuto di una lista filtrata di persone sia uguale a quello del file originario (filtrato).
Data una lista di nodi del tipo #node la scorre confrontando i nodi con il valore atteso. Viene richiamata nella funzione test_people_to_file_cf_males_AL che testa le persone filtrate con cognome compreso tra A-L e sesso maschile.
Parameters
list_people Lista di persone
Definition at line 874 of file test_cfutils.c.
Referenced by test_people_to_file_cf_males_AL().
void ctrl_FILE_MZ_female (list * list_people)
Verifica che il contenuto di una lista filtrata di persone sia uguale a quello del file originario (filtrato).
Data una lista di nodi del tipo #node la scorre confrontando i nodi con il valore atteso. Viene richiamata nella funzione test_people_to_file_cf_females_MZ che testa le persone filtrate con cognome compreso tra M-Z e sesso femminile.
Parameters
list_people Lista di persone
Definition at line 930 of file test_cfutils.c.
Referenced by test_people_to_file_cf_females_MZ().
void ctrl_full_FILE (list * list_people)
Verifica che il contenuto di una lista di persone sia uguale a quello del file originario.
Data una lista di nodi del tipo #node la scorre confrontando i nodi con il valore atteso. Viene richiamata nelle funzioni che testano le persone, ovvero test_generate_cfs e test_people_to_file_cf
Parameters
list_people Lista di persone
Definition at line 726 of file test_cfutils.c.
Referenced by test_generate_cfs(), and test_people_to_file_cf().
int init_suite_default (void)
Definition at line 653 of file test_cfutils.c.
Referenced by main().
int main ()
Definition at line 661 of file test_cfutils.c.
References clean_suite_default(), init_suite_default(), test_filter_people(), test_generate_cfs(), test_is_female(), test_is_male(), test_is_surname_AL(), test_is_surname_MZ(), test_list_to_file(), test_list_to_file_females_MZ(), test_list_to_file_males_AL(), test_outfile_path(), test_people_file_to_list(), test_people_to_file_cf(), test_people_to_file_cf_females_MZ(), test_people_to_file_cf_males_AL(), test_read_birth_place_code(), and test_read_person().
void test_filter_people (void)
Definition at line 103 of file test_cfutils.c.
Referenced by main().
void test_generate_cfs (void)
Definition at line 150 of file test_cfutils.c.
References ctrl_full_FILE().
Referenced by main().
void test_is_female (void)
Definition at line 55 of file test_cfutils.c.
Referenced by main().
void test_is_male (void)
Definition at line 44 of file test_cfutils.c.
Referenced by main().
void test_is_surname_AL (void)
Definition at line 67 of file test_cfutils.c.
Referenced by main().
void test_is_surname_MZ (void)
Definition at line 85 of file test_cfutils.c.
Referenced by main().
void test_list_to_file (void)
Definition at line 265 of file test_cfutils.c.
Referenced by main().
void test_list_to_file_females_MZ (void)
Definition at line 378 of file test_cfutils.c.
Referenced by main().
void test_list_to_file_males_AL (void)
Definition at line 340 of file test_cfutils.c.
Referenced by main().
void test_outfile_path (void)
Definition at line 613 of file test_cfutils.c.
Referenced by main().
void test_people_file_to_list (void)
Definition at line 225 of file test_cfutils.c.
Referenced by main().
void test_people_to_file_cf (void)
Definition at line 416 of file test_cfutils.c.
References ctrl_full_FILE().
Referenced by main().
void test_people_to_file_cf_females_MZ (void)
Definition at line 548 of file test_cfutils.c.
References ctrl_FILE_MZ_female().
Referenced by main().
void test_people_to_file_cf_males_AL (void)
Definition at line 484 of file test_cfutils.c.
References ctrl_FILE_AL_male().
Referenced by main().
void test_read_birth_place_code (void)
Definition at line 164 of file test_cfutils.c.
Referenced by main().
void test_read_person (void)
Definition at line 184 of file test_cfutils.c.
Referenced by main().