cfgenerator_634850_633646: cfgenerator.c File Reference
cfgenerator.c File Reference
#include "cfgenerator.h"
Functions
static bool has_valid_chars (const char text[])
static bool is_uppercase (const char code[])
static bool has_numbers_and_2separators (const char str[])
static bool is_correct_format_date (const char str[])
static bool has_correct_format_datecode (const char str[])
static bool has_correct_format_birth_place_code (const char str[])
static void init_array (char a[], int l)
static int compactify (const char org_str[], char comp_str[])
static bool is_vowel (const char ch)
static int get_consonants (const char str[], char consonants[])
static int get_vowels (const char str[], char vowels[])
static void add_3_chars_name (const char str[], char code[])
static void add_3_chars (const char str[], char code[])
static int add_2_chars (const char str[], char code[], int from)
static int add_1_char (const char str[], char code[], int from)
static void add_special_char (char code[], int from)
static void code_year (const char date[], char coded_date[])
static void code_month (const char date[], char coded_date[])
static void code_day (const char date[], char sex, char coded_date[])
static int odd_char2code (char cf_code)
static int even_char2code (char cf_code)
static char reminder2code (int value)
void surname2code (const char org_surname[], char coded_surname[])
void name2code (const char org_name[], char coded_name[])
void date2code (const char date[], const char sex, char coded_date[])
char cf_ctrl_code (const char coded_surname[], const char coded_name[], const char coded_date[], const char birth_place_code[])
void cf_generator (const char surname[], const char name[], const char date[], const char birth_place_code[], const char sex, char cf[])
Function Documentation
static int add_1_char (const char str[], char code[], int from) static
Definition at line 243 of file cfgenerator.c.
Referenced by name2code(), and surname2code().
static int add_2_chars (const char str[], char code[], int from) static
Definition at line 233 of file cfgenerator.c.
Referenced by name2code(), and surname2code().
static void add_3_chars (const char str[], char code[]) static
Definition at line 225 of file cfgenerator.c.
Referenced by name2code(), and surname2code().
static void add_3_chars_name (const char str[], char code[]) static
Definition at line 213 of file cfgenerator.c.
Referenced by name2code().
static void add_special_char (char code[], int from) static
Definition at line 250 of file cfgenerator.c.
Referenced by name2code(), and surname2code().
char cf_ctrl_code (const char coded_surname[], const char coded_name[], const char coded_date[], const char coded_birth_place[])
Calcola il codice di controllo di un codice fiscale (l'ultimo carattere).
Parameters
coded_surname Cognome codificato (stringa da 3 caratteri).
coded_name Nome codificato (stringa da 3 caratteri).
coded_date Data di nascita codificata (stringa da 5 caratteri).
coded_birth_place Codice catastale del luogo di nascita (striga da 4 caratteri).
Returns
Carattere di controllo.
Precondition
coded_surname deve essere una stringa di 3 caratteri maiuscoli.
coded_name deve essere una stringa di 3 caratteri maiuscoli.
coded_date deve essere una stringa di 5 caratteri (2 numeri, 1 lettera, 2 numeri)
birth_place_code deve essere una stringa di 4 caratteri (1 lettera, 3 numeri)
Postcondition
il carattere di controllo deve essere una lettera maiuscola.
Definition at line 650 of file cfgenerator.c.
References CODED_BIRTH_PLACE_LENGTH, CODED_DATE_LENGTH, CODED_NAME_LENGTH, CODED_SRN_LENGTH, even_char2code(), has_correct_format_birth_place_code(), has_correct_format_datecode(), is_uppercase(), LETTERS, odd_char2code(), reminder2code(), and TEST_CF_LENGTH.
Referenced by cf_generator().
void cf_generator (const char surname[], const char name[], const char date[], const char birth_place_code[], const char sex, char cf[])
Calcola il codice fiscale di una persona.
Parameters
surname Cognome.
name Nome.
date Data di nascita.
birth_place_code Codice catastale del luogo di nascita.
sex Sesso.
cf Codice fiscale (inizializzato a stringa vuota "").
Precondition
surname puo' contenere solo caratteri maiuscoli, spazi, apici.
surname deve essere formato da almeno due caratteri.
name puo' contenere solo caratteri maiuscoli, spazi, apici.
name deve essere formato da almeno due caratteri.
date puo' contenere solo numeri e 2 caratteri separatori '/'
date deve essere fornita nel formato GG/MM/AAAA con 0 < GG <= 31 ; 0 < MM <= 12; 1900 < AAAA <= 2015
birth_place_code codice catastale del luogo di nascita composto da una lettera e tre cifre
sex puo' essere 'M' o 'F'
cf deve poter almeno contenere una stringa di 16 caratteri (piu' il carattere terminatore)
Postcondition
cf deve essere una stringa composta da (in ordine): 6 lettere, 2 numeri, 1 lettera, 2 numeri, 1 lettera, 3 numeri, 1 lettera
Definition at line 692 of file cfgenerator.c.
References cf_ctrl_code(), CODED_DATE_LENGTH, CODED_NAME_LENGTH, CODED_SRN_LENGTH, date2code(), DATE_ORG_LENGTH, EOS, has_numbers_and_2separators(), has_valid_chars(), init_array(), is_correct_format_date(), MIN_NAME_LENGTH, MIN_SURNAME_LENGTH, name2code(), surname2code(), and TEST_CF_LENGTH.
Referenced by generate_cfs().
static void code_day (const char date[], char sex, char coded_date[]) static
Definition at line 277 of file cfgenerator.c.
References CODED_DAY_INDEX, DATE_DIGITS, DAY_INDEX, EOS, and FEMALE_DAYS_OFFSET.
Referenced by date2code().
static void code_month (const char date[], char coded_date[]) static
Definition at line 264 of file cfgenerator.c.
References CODED_MONTH_INDEX, DATE_DIGITS, and MONTH_INDEX.
Referenced by date2code().
static void code_year (const char date[], char coded_date[]) static
Definition at line 256 of file cfgenerator.c.
References CODED_YEAR_INDEX, DATE_DIGITS, and YEAR_INDEX.
Referenced by date2code().
static int compactify (const char org_str[], char comp_str[]) static
Definition at line 141 of file cfgenerator.c.
References EOS.
Referenced by name2code(), and surname2code().
void date2code (const char date[], const char sex, char coded_date[])
Codifica la data di nascita nel formato per codice fiscale.
Parameters
date Data di nascita nel formato GG/MM/AAAA.
sex Sesso.
coded_date Stringa di 5 caratteri che conterra' la codifica.
Precondition
date puo' contenere solo numeri e 2 caratteri separatori '/'
date deve essere fornita nel formato GG/MM/AAAA con 0 < GG <= 31 ; 0 < MM <= 12; 1900 < AAAA <= 2015
sex puo' essere 'M' o 'F'
coded_date deve poter contenere una striga di 5 caratteri (piu' il carattere terminatore)
Postcondition
coded_date deve essere una stringa di 5 caratteri
deve esser composta da (in ordine): 2 cifre, 1 lettera, 2 cifre
Definition at line 633 of file cfgenerator.c.
References code_day(), code_month(), code_year(), CODED_DATE_LENGTH, EOS, has_correct_format_datecode(), has_numbers_and_2separators(), and is_correct_format_date().
Referenced by cf_generator().
static int even_char2code (char cf_code) static
Definition at line 419 of file cfgenerator.c.
Referenced by cf_ctrl_code().
static int get_consonants (const char str[], char consonants[]) static
Definition at line 180 of file cfgenerator.c.
References EOS, and is_vowel().
Referenced by name2code(), and surname2code().
static int get_vowels (const char str[], char vowels[]) static
Definition at line 196 of file cfgenerator.c.
References EOS, and is_vowel().
Referenced by name2code(), and surname2code().
static bool has_correct_format_birth_place_code (const char str[]) static
Definition at line 115 of file cfgenerator.c.
References EOS.
Referenced by cf_ctrl_code().
static bool has_correct_format_datecode (const char str[]) static
Definition at line 93 of file cfgenerator.c.
References CODED_DAY_INDEX, CODED_MONTH_INDEX, and EOS.
Referenced by cf_ctrl_code(), and date2code().
static bool has_numbers_and_2separators (const char str[]) static
Definition at line 42 of file cfgenerator.c.
References EOS.
Referenced by cf_generator(), and date2code().
static bool has_valid_chars (const char text[]) static
Definition at line 14 of file cfgenerator.c.
References EOS.
Referenced by cf_generator(), name2code(), and surname2code().
static void init_array (char a[], int l) static
Definition at line 136 of file cfgenerator.c.
References EOS.
Referenced by cf_generator(), name2code(), and surname2code().
static bool is_correct_format_date (const char str[]) static
Definition at line 59 of file cfgenerator.c.
References DATE_DIGITS, EOS, MONTH_INDEX, and YEAR_INDEX.
Referenced by cf_generator(), and date2code().
static bool is_uppercase (const char code[]) static
Definition at line 28 of file cfgenerator.c.
References EOS.
Referenced by cf_ctrl_code(), name2code(), and surname2code().
static bool is_vowel (const char ch) static
Definition at line 155 of file cfgenerator.c.
Referenced by get_consonants(), and get_vowels().
void name2code (const char name[], char coded_name[])
Codifica il nome nel formato per codice fiscale.
Parameters
name Nome.
coded_name Stringa da 3 caratteri che conterra' la codifica.
Precondition
name puo' contenere solo caratteri maiuscoli, spazi, apici.
name deve essere formato da almeno due caratteri.
coded_name deve essere una stringa di 3 caratteri
Postcondition
coded_name deve contenere 3 lettere maiuscole.
Definition at line 589 of file cfgenerator.c.
References add_1_char(), add_2_chars(), add_3_chars(), add_3_chars_name(), add_special_char(), CODED_NAME_LENGTH, compactify(), EOS, get_consonants(), get_vowels(), has_valid_chars(), init_array(), is_uppercase(), MIN_CONSONANT, and MIN_NAME_LENGTH.
Referenced by cf_generator().
static int odd_char2code (char cf_code) static
Definition at line 301 of file cfgenerator.c.
Referenced by cf_ctrl_code().
static char reminder2code (int value) static
Definition at line 538 of file cfgenerator.c.
Referenced by cf_ctrl_code().
void surname2code (const char org_surname[], char coded_surname[])
Codifica il cognome nel formato per codice fiscale.
Parameters
org_surname Nome.
coded_surname Stringa da 3 caratteri che conterra' la codifica.
Precondition
surname puo' contenere solo caratteri maiuscoli, spazi, apici.
surname deve essere formato da almeno due caratteri.
coded_surname deve essere una stringa di 3 caratteri
Postcondition
coded_surname deve contenere 3 lettere maiuscole.
Definition at line 547 of file cfgenerator.c.
References add_1_char(), add_2_chars(), add_3_chars(), add_special_char(), CODED_SRN_LENGTH, compactify(), EOS, get_consonants(), get_vowels(), has_valid_chars(), init_array(), is_uppercase(), and MIN_SURNAME_LENGTH.
Referenced by cf_generator().