cfgenerator_634850_633646: utils/cfutils.c File Reference
cfutils.c File Reference
#include "cfutils.h"
Functions
bool is_male (const person *data)
bool is_female (const person *data)
bool is_surname_AL (const person *data)
bool is_surname_MZ (const person *data)
void filter_people (list *people_list, filter_fn filter)
void generate_cfs (list *people_list, FILE *places_file)
char * read_birth_place_code (FILE *places_file, const char *birth_place)
person * read_person (FILE *people_file)
list * people_file_to_list (FILE *people_file)
void list_to_file (list *people_list, FILE *output_file)
void list_to_file_males_AL (list *people_list, FILE *output_file)
void list_to_file_females_MZ (list *people_list, FILE *output_file)
void people_to_file_cf (FILE *people_file, FILE *output_file, FILE *places_file)
void people_to_file_cf_males_AL (FILE *people_file, FILE *output_file, FILE *places_file)
void people_to_file_cf_females_MZ (FILE *people_file, FILE *output_file, FILE *places_file)
char * outfile_path (char *wd_path, char *filename)
Detailed Description
Author
Francesco Sanzone f.san.nosp@m.zone.nosp@m.@stud.nosp@m.enti.nosp@m..unib.nosp@m.a.it 634850
Francesco Piccinni f.pic.nosp@m.cinn.nosp@m.i5@st.nosp@m.uden.nosp@m.ti.un.nosp@m.iba..nosp@m.it 633646
Date
03/giu/2015
Definition in file cfutils.c.
Function Documentation
void filter_people (list * people_list, filter_fn filter)
Filtra le persone presenti in una lista di persone in base ad una funzione di filtraggio.
Parameters
[in,out] people_list puntatore a list contenente un numero di nodi pari alle persone lette da file
[in] filter puntatore a funzione del tipo filter_fn
Precondition
puntatore a lista di persone people_list non NULL
puntatore a funzione filter non NULL
Definition at line 107 of file cfutils.c.
References content(), delete_node(), head(), length(), next(), and remove_node().
Referenced by list_to_file_females_MZ(), and list_to_file_males_AL().
void generate_cfs (list * people_list, FILE * places_file)
Genera il codice fiscale delle persone presenti nella lista
Parameters
[in,out] people_list puntatore a list contenente un numero di nodi pari alle persone lette da file
[in] places_file puntatore a stream in lettura collegato al file dei comuni con i codici catastali
Precondition
puntatore a lista di persone people_list non NULL
puntatore a stream places_file non NULL
Definition at line 138 of file cfutils.c.
References cf_generator(), content(), head(), length(), next(), and read_birth_place_code().
Referenced by people_to_file_cf(), people_to_file_cf_females_MZ(), and people_to_file_cf_males_AL().
bool is_female (const person * data)
Controlla se il sesso di una persona e' femminile.
Parameters
[in] data puntatore a struttura person contenente i dati anagrafici di una persona.
Returns
true se donna, false altrimenti
Precondition
puntatore a struttura person non NULL
Definition at line 41 of file cfutils.c.
References person_struct::sex.
Referenced by list_to_file_females_MZ().
bool is_male (const person * data)
Controlla se il sesso di una persona e' maschile.
Parameters
[in] data puntatore a struttura person contenente i dati anagrafici di una persona.
Returns
true se maschio, false altrimenti.
Precondition
puntatore a struttura person non NULL
Definition at line 19 of file cfutils.c.
References person_struct::sex.
Referenced by list_to_file_males_AL().
bool is_surname_AL (const person * data)
Controlla se il cognome di una persona inizia con una lettera compresa tra A-L
Parameters
[in] data puntatore a struttura person contenente i dati anagrafici di una persona.
Returns
true se il cognome inizia con una lettera compresa tra A-L, false altrimenti
Precondition
puntatore a struttura person non NULL
Definition at line 63 of file cfutils.c.
References person_struct::surname.
Referenced by list_to_file_males_AL().
bool is_surname_MZ (const person * data)
Controlla se il cognome della persona inizia con una lettera compresa tra M-Z
Parameters
[in] data puntatore a struttura person contenente i dati anagrafici di una persona.
Returns
true se il cognome inizia con una lettera compresa tra M-Z, false altrimenti
Precondition
puntatore a struttura person non NULL
Definition at line 84 of file cfutils.c.
References person_struct::surname.
Referenced by list_to_file_females_MZ().
void list_to_file (list * people_list, FILE * output_file)
Stampa su file i dati anagrafici delle persone in lista
Parameters
[in] people_list puntatore a list contenente un numero di nodi pari alle persone lette da file
[in] output_file puntatore a strem in scrittura associato ad un file
Precondition
puntatore a people_list non NULL
puntatore a output_file non NULL
Definition at line 287 of file cfutils.c.
References content(), head(), length(), and next().
Referenced by list_to_file_females_MZ(), list_to_file_males_AL(), and people_to_file_cf().
void list_to_file_females_MZ (list * people_list, FILE * output_file)
Filtra una lista preservando individui di sesso femminile con cognome compreso tra M-Z
Parameters
[in] people_list puntatore a list contenente un numero di nodi pari alle persone lette da file
[in] output_file puntatore a strem in scrittura associato ad un file
Precondition
puntatore a people_list non NULL
puntatore a output_file non NULL
Definition at line 345 of file cfutils.c.
References filter_people(), is_female(), is_surname_MZ(), and list_to_file().
Referenced by people_to_file_cf_females_MZ().
void list_to_file_males_AL (list * people_list, FILE * output_file)
Filtra una lista preservando individui di sesso maschile con cognome compreso tra A-L
Parameters
[in] people_list puntatore a list contenente un numero di nodi pari alle persone lette da file
[in] output_file puntatore a strem in scrittura associato ad un file
Precondition
puntatore a people_list non NULL
puntatore a output_file non NULL
Definition at line 326 of file cfutils.c.
References filter_people(), is_male(), is_surname_AL(), and list_to_file().
Referenced by people_to_file_cf_males_AL().
char* outfile_path (char * wd_path, char * filename)
Genera il path assoluto di filename
Parameters
[in] wd_path path assoluto della directory di lavoro in cui salvare i file di output
[in] filename nome del file di output
Returns
path assoluto del filename
Precondition
wd_path deve terminare con il carattere separatore (\ per Win e / per linux) da specificare in OS_SEP
Postcondition
la lunghezza del path ritornato deve essere somma delle lunghezze di wd_path e filename
Definition at line 452 of file cfutils.c.
References OS_SEP.
list* people_file_to_list (FILE * people_file)
Legge i dati anagrafici delle persone presenti nel file di input.
Parameters
[in] people_file puntatore a stream in lettura collegato al file con i dati anagrafici delle persone (senza codice fiscale)
Returns
puntatore ad una struttura list
Precondition
puntatore allo stream people_file non NULL
Postcondition
puntatore alla lista creata non NULL
Definition at line 259 of file cfutils.c.
References add_node(), head(), new_list(), new_node(), read_person(), and tail().
Referenced by people_to_file_cf(), people_to_file_cf_females_MZ(), and people_to_file_cf_males_AL().
void people_to_file_cf (FILE * people_file, FILE * output_file, FILE * places_file)
Legge i dati anagrafici di persone da un file e li riscrive in un altro file aggiungendovi il codice fiscale
Parameters
[in] people_file
[in] output_file
[in] places_file
Precondition
il puntatore allo stream people_file non deve essere NULL
il puntatore allo stream output_file non deve essere NULL
il puntatore allo stream places_file non deve essere NULL
Definition at line 367 of file cfutils.c.
References generate_cfs(), list_to_file(), and people_file_to_list().
void people_to_file_cf_females_MZ (FILE * people_file, FILE * output_file, FILE * places_file)
Legge i dati anagrafici di persone da un file, filtra i risultati e li riscrive in un altro file aggiungendovi il codice fiscale
Parameters
[in] people_file
[in] output_file
[in] places_file
Precondition
il puntatore allo stream people_list non deve essere NULL
il puntatore allo stream output_file non deve essere NULL
il puntatore allo stream places_file non deve essere NULL
Definition at line 423 of file cfutils.c.
References generate_cfs(), list_to_file_females_MZ(), and people_file_to_list().
void people_to_file_cf_males_AL (FILE * people_file, FILE * output_file, FILE * places_file)
Legge i dati anagrafici di persone da un file, filtra i risultati e li riscrive in un altro file aggiungendovi il codice fiscale
Parameters
[in] people_file
[in] output_file
[in] places_file
Precondition
il puntatore allo stream people_file non deve essere NULL
il puntatore allo stream output_file non deve essere NULL
il puntatore allo stream places_file non deve essere NULL
Definition at line 395 of file cfutils.c.
References generate_cfs(), list_to_file_males_AL(), and people_file_to_list().
char* read_birth_place_code (FILE * places_file, const char * birth_place)
Legge il codice catastale di un comune
Parameters
[in] places_file puntatore a stream in lettura collegato al file dei comuni con i codici catastali
[in] birth_place stringa con il nome del comune di nascita
Returns
la stringa del codice catastale del comune di nascita
Precondition
puntatore a stream places_file non NULL
birth_place stringa non vuota
Postcondition
il puntatore alla stringa del codice catastale ritornato non NULL
il codice catastale restituito deve essere una stringa di 4 caratteri
Definition at line 174 of file cfutils.c.
Referenced by generate_cfs().
person* read_person (FILE * people_file)
Legge i dati anagrafici di una singola persona come blocco di informazioni (il codice fiscale non e' presente)
Parameters
[in] people_file puntatore a stream in lettura collegato al file con i dati anagrafici delle persone (senza codice fiscale)
Returns
puntatore ad una struttura person con i campi opportunamente avvalorati (il campo person::cf inizializzato a "" - stringa vuota)
Precondition
puntatore a people_file non NULL
Postcondition
il puntatore restituito non e' NULL
Definition at line 223 of file cfutils.c.
References person_struct::birth_date, person_struct::birth_place, person_struct::cf, person_struct::name, person_struct::sex, and person_struct::surname.
Referenced by people_file_to_list().