cfgenerator_634850_633646: list/list.c File Reference
list.c File Reference
#include <assert.h>
#include "list.h"
Data Structures
struct node
struct list_struct
Functions
list * new_list (void)
node * new_node (list_type content)
list_type content (node *n)
node * head (const list *l)
node * tail (const list *l)
int length (const list *l)
node * next (const list *l, node *n)
node * prev (const list *l, node *n)
void add_node (list *l, node *node_before, node *node_to_add)
void remove_node (list *l, node *node_to_remove)
void delete_list (list *l)
void delete_node (node *n)
node * lookfor (const list *l, list_type cont)
Function Documentation
void add_node (list * l, node * node_before, node * node_to_add)
Aggiunge un nodo alla lista. La procedura aggiunge un nodo nella lista dopo il nodo specificato node_before. Per esempio, se la lista e' costituita dalla sequenza di nodi (A,B,C) e node_before e' A, allora a seguito dell'aggiunta del nodo D la lista sara' trasformata in (A,D,B,C). Se node_before e' NULL, per convenzione l'inserimento del nodo avviene in testa alla lista.
Precondition
l non puo' essere NULL
node_to_add non deve essere NULL
Parameters
l la lista a cui aggiungere un nodo
node_before il nodo dopo il quale sara' aggiunto il nodo
node_to_add il nodo da aggiungere alla lista
Definition at line 72 of file list.c.
References list_struct::head, list_struct::length, node::next, node::previous, and list_struct::tail.
Referenced by people_file_to_list().
list_type content (node * n)
Restituisce il contenuto di un nodo.
Precondition
Il nodo non puo' essere NULL.
Parameters
n il nodo da cui estrarre il contenuto
Returns
il contenuto estratto dal nodo.
Definition at line 34 of file list.c.
References node::content.
Referenced by filter_people(), generate_cfs(), list_to_file(), lookfor(), and new_node().
void delete_list (list * l)
Distrugge la lista. La distruzione della lista comporta la distruzione di tutti i nodi che la costituiscono.
Precondition
l non deve essere null
Parameters
l la lista da distruggere
Definition at line 132 of file list.c.
References delete_node(), head(), next(), and remove_node().
void delete_node (node * n)
Distrugge un nodo. Il nodo deve essere preventivamente rimosso dalla lista cui apparteneva, utilizzando la funzione #remove.
Precondition
n non deve essere null
Parameters
n il nodo da distruggere
Definition at line 146 of file list.c.
Referenced by delete_list(), and filter_people().
node* head (const list * l)
Restituisce la testa della lista. La testa della lista e' il primo nodo della sequenza che costituisce la lista. Se la lista e' vuota, la funzione restituisce NULL.
Precondition
l non puo' essere NULL
Parameters
l la lista da cui estrarre la testa.
Returns
la testa della lista.
Definition at line 40 of file list.c.
References list_struct::head.
Referenced by delete_list(), filter_people(), generate_cfs(), list_to_file(), lookfor(), and people_file_to_list().
int length (const list * l)
Restituisce la lunghezza della lista. La lunghezza di una lista e' il numero di nodi appartenenti alla lista.
Precondition
l non puo' essere NULL
Parameters
l la lista da cui ricavare la lunghezza
Returns
la lunghezza della lista.
Definition at line 52 of file list.c.
References list_struct::length.
Referenced by filter_people(), generate_cfs(), and list_to_file().
node* lookfor (const list * l, list_type content)
Cerca un nodo della lista sulla base del contenuto. La funzione ricerca un nodo della lista che contenga il contenuto specificato da content. La funzione restituisce il primo nodo trovato con il contenuto specificato, oppure NULL se nessun nodo possiede il contenuto specificato.
Precondition
l non deve essere NULL
Parameters
l la lista su cui effettuare la ricerca
content il contenuto da ricercare
Returns
il nodo che contiene il contenuto ricercato oppure NULL
Definition at line 151 of file list.c.
References content(), head(), and next().
list* new_list (void)
Costruisce una lista vuota. Una lista vuota ha lunghezza 0, non ha testa, ne' coda. Le liste costruite devono essere distrutte con la funzione #delete. Se la funzione restitusce NULL, allora la lista non puo' essere creata.
Returns
una nuova lista vuota
Definition at line 16 of file list.c.
References list_struct::head, list_struct::length, and list_struct::tail.
Referenced by people_file_to_list().
node* new_node (list_type content)
Costruisce un nuovo nodo. Un nodo appena costruito non appartiene ad alcuna lista, ma contiene il contenuto specificato. Esso non puo' essere utilizzato, fintantoche' non viene inserito in una lista. I nodi inseriti in una lista sono distrutti dalla funzione delete_list. Per distruggere un nodo non in lista, usare la funzione delete_node. Se la funzione restituisce NULL, allora il nodo non puo' essere creato.
Parameters
content il contenuto del nodo
Returns
un puntatore al nodo costruito.
Definition at line 25 of file list.c.
References node::content, content(), node::next, and node::previous.
Referenced by people_file_to_list().
node* next (const list * l, node * n)
Restituisce l'elemento successivo al nodo specificato della lista. Se il nodo e' in coda alla lista, restituisce NULL.
Precondition
l non puo' essere NULL
il nodo deve appartenere alla lista.
Parameters
l la lista cui appartiene il nodo.
n il nodo da cui ricavare il successore
Returns
il successore del nodo n nella lista l.
Definition at line 58 of file list.c.
References node::next.
Referenced by delete_list(), filter_people(), generate_cfs(), list_to_file(), and lookfor().
node* prev (const list * l, node * n)
Restituisce l'elemento precedente al nodo specificato della lista. Se il nodo e' in testa alla lista, restituisce NULL.
Precondition
l non puo' essere NULL
il nodo deve appartenere alla lista.
Parameters
l la lista cui appartiene il nodo.
n il nodo da cui ricavare il predecessore
Returns
il predecessore del nodo n nella lista l.
Definition at line 65 of file list.c.
References node::previous.
void remove_node (list * l, node * node_to_remove)
Rimuove un nodo dalla lista. La procedura NON distrugge il nodo eliminato.
Precondition
l non deve essere NULL
il nodo da rimuovere deve appartenere alla lista
Parameters
l la lista contenente il nodo da rimuovere
node_to_remove il nodo da rimuovere.
Definition at line 102 of file list.c.
References list_struct::head, list_struct::length, node::next, node::previous, and list_struct::tail.
Referenced by delete_list(), and filter_people().
node* tail (const list * l)
Restituisce la coda della lista. La coda della lista e' l'ultimo elemento della sequenza che costituisce la lista. Se la lista e' vuota, la funzione restituisce NULL.
Precondition
l non puo' essere NULL.
Parameters
l la lista da cui estrarre la coda
Returns
la coda della lista.
Definition at line 46 of file list.c.
References list_struct::tail.
Referenced by people_file_to_list().